### ISSUE TITLE
Ability to change the radius

### ISSUE THREAD

**Issue by mccartney** [adam-lynch/back-of-your-hand#14]
(BTW: I saw your post in HN, thanks for sharing, I have "always" dreamed about a game like this)

**What**: Would it be an option to select a bigger radius? I'd like to take ~15km for the whole city I live in.

**Why**: With my local neighborhood the game is boring as I know it all (495/500). I'd like to learn a bigger area.

**Comment by adam-lynch** [comment]
Interesting, thanks for the feedback! It's semi-related to #5

Just to be safe, you know you can change the location right? For now at least, you could select different areas of the city.

**Comment by adam-lynch** [comment]
This would also help in the case where there are simply not enough streets and it shows "There aren't enough streets in this area. Please select somewhere else"

**Comment by adam-lynch** [comment]
I'm going to use this issue as a catch-all for all requests for changing the radius, including making it smaller. there were a few comments on [Hacker News](https://news.ycombinator.com/item?id=30733339) about making it smaller. I wonder is it better to think about the number of streets rather than a radius, not sure

**Comment by adam-lynch** [comment]
Most people have complained that the radius is too large so for now I've reduced it by 20%

**Comment by mccartney** [comment]
> you know you can change the location right?

Yes. I do. The radius to be bigger would be a nice-to-have.
