### ISSUE TITLE
The no-streets map tiles are no longer available

### ISSUE THREAD

**Issue by alansartorio** [adam-lynch/back-of-your-hand#7]
According to [this comment by TheDJ](https://phabricator.wikimedia.org/T187601#7642399), all tiles from tiles.wmflabs.org are no longer available.

**Comment by adam-lynch** [comment]
Ugh, I missed the notification for this but thanks so much for pointing it out. You even found the forum post that I couldn't! That would've saved me some time! 

I discovered the issue myself and initially [patched it](https://github.com/adam-lynch/back-of-your-hand/commit/9fa96ba06bfd23622111cb19f6e710f6487ac501) by always showing street names. I actually set up some monitoring to email when any of these URLs stop working, but it didn't because they still returned an image.

I looked into generating the tiles myself but that takes a lot of time and storage; 

> ...300GB+ of fast storage, 24GB of memory, and a quad-core processor for the entire planet.
> We would recommend that you begin with extracts of OpenStreetMap data – for example, a city, county or small country – rather than spending a week importing the whole world (planet.osm) and then having to restart because of a configuration mistake!

\- From [Serving Tiles](https://switch2osm.org/serving-tiles/)

I've now fixed it in #8 by using two custom [Maptiler](https://maptiler.com) maps as layers (one has everything but names and the other only has names). Downsides:

- More JavaScript dependencies (`mapbox-gl` and `mapbox-gl-leaflet` as an adapter). I had to pin the `mapbox-gl` dependency to a specific version because [panning was broken](https://github.com/mapbox/mapbox-gl-leaflet/issues/145) on the latest version.
- Maptiler doesn't allow raster tiles usage for custom maps on their free plan.
- Mapbox sends events / analytics requests.
- Now have to worry about Maptiler _and_ Mapbox  usage limits.
- To me it feels a little slower when tiles are loaded (Lighthouse still rates the page at 100/100 for performance on desktop though).

A better solution (which I found via to the forum post you linked, thanks): #10
